# Generated by Django 5.1.3 on 2024-11-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='age_limited',
            field=models.BooleanField(default=True),
        ),
    ]
